"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Customer_1 = require("./Customer");
var cust1 = new Customer_1.Customer(101, "Sam");
console.log("ID: " + cust1.customerID);
console.log("Name: " + cust1.customerName);
cust1.customerName = "Tom";
console.log("New Name: " + cust1.customerName);
cust1.customerID = 102;
console.log("New ID: " + cust1.customerID);
var add1 = new Customer_1.Address('Mumbai');
console.log('Address: ' + add1.address);
