package com.techlab.demo.Assignment;

import java.util.Scanner;

public class GameTest {

	static boolean gameStarted = false;
	static Scanner scan = new Scanner(System.in);

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		GameTest games = new GameTest();

		// Scanner scan = new Scanner(System.in);
		int choice = 0;
		boolean endGame = false;
		final int START_GAME = 1;
		final int RESTART_GAME = 2;
		final int END_GAME = 3;

		System.out.println("Enter your choice");
		System.out.println("1. Start Game.\n2. Restart Game.\n3. Exit ");
		choice = scan.nextInt();

		do {

			switch (choice) {

			case START_GAME:
				games.startGame();
				gameStarted = true;
				break;

			case RESTART_GAME:
				// Game cannot be restarted before it is played once.
//				if (!gameStarted) {
//					System.out.println("Please first start the game");
//					break;
//				} else {
//					System.out.println("Would you like to play the game again?(y|n)");
//					String restartChoice = scan.next();
//
//					if (restartChoice.toLowerCase().equals("y")) {
//						gameTest.startGame();
//						break;
//					} else {
//						endGame = true;
//						break;
//					}
//				}
				
				endGame = games.restartGame();
				break;

			case END_GAME:
				endGame = true;
				break;

			default:
				System.out.println("Enter valid choice");
			}

			if (!endGame) {
				System.out.println("Enter your choice");
				System.out.println("1. Start Game.\n2. Restart Game.\n3. Exit ");
				choice = scan.nextInt();
			}

		} while (!endGame);

		System.out.println("Thanks for playing the game");
	}

	void startGame() {

		int countGuess = 0;
		int max = 9;
		int min = 1;
		int range = max - min + 1;
		boolean guess = false;

		int randomNumber = (int) (Math.random() * range);
		// System.out.println(randomNumber);
		// Get User Input

		while (!guess) {
			System.out.print("Enter your guess: ");
			int accpetUserNumber = scan.nextInt();
			countGuess++;

			if (randomNumber != accpetUserNumber) {
				if (accpetUserNumber < randomNumber) {
					System.out.println("Hint: Your guess is low");
				} else {
					System.out.println("Hint: Your guess is high");

				}
			} else {
				if (randomNumber % 2 == 0) {
					System.out.println("Congratualtions!! You have guessed right number and your number is even");
				} else {
					System.out.println("Congratualtions!! You have guessed right number and your number is odd");
				}

				System.out.println("Your number was : " + randomNumber);
				System.out.println("Number of trails : " + countGuess);
				guess = true;
			}

		}
		// scannerGame.close();
	}

	boolean restartGame() {
		boolean userAnswer = false;
		if (!gameStarted) {
			System.out.println("Please Start the game");
		} else {
			System.out.println("Would you like to restart the game?(y|n)");
			String restartChoice = scan.next();

			if (restartChoice.toLowerCase().equals("y")) {
				startGame();
			} else {
				userAnswer = true;
			}
		}
		return userAnswer;
	}

}

// print 2 more things on screen as follows
// 1. your number was : randomNumber generated by sys (done)
// 2. number of trails: (done)
// 3. check whether u are voilating magic num of dry principle

// yes
//yes case 2
//no mam like for restart i have used the original startGame method
